site_name: Simple-AV
site_url: https://tlab-wide.github.io/simple_av/

theme:
  language: en
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.path
    - navigation.footer
    - content.tabs.link
    - search.suggest
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra:
  version:
    provider: mike

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Getting started:
      - Setting up the System: Simple-AV/SystemSetup/index.md
      - Quick Start Demo: GettingStarted/QuickStartDemo/index.md
  - Project guide:
      - Git Branch: ProjectGuide/GitBranch/index.md
  - Simple-AV:
      - Waypoint Map (*.json): Simple-AV/JsonMap/index.md
      - Modules:
          - Common: Simple-AV/Modules/Common/index.md
          - Localization: Simple-AV/Modules/Localization/index.md
          - Planning: Simple-AV/Modules/Planning/index.md
          - Perception: Simple-AV/Modules/Perception/index.md
          - Control: Simple-AV/Modules/Control/index.md
          - System: Simple-AV/Modules/System/index.md
  - New Features:
      - Road Side Units (RSU): NewFeatures/RSU/index.md
      - Traffic Signal Fusion: NewFeatures/TrafficSignalAwareness/index.md