# Traffic Light Configuration
traffic_light:
  enable: True   # Enable or disable traffic lights
  use_rsu: True  # Enable or disable RSU for traffic lights

# Object Detection Configuration
object_detection:
  enable: True  # Enable or disable object detection
  use_rsu: False # Enable or disable RSU for Object Detection
  direction_filter:
    lateral_threshold: 2.25 # meters; |y| <= threshold is "straight ahead" in vehicle frame
    allowed_directions: ["above", "NW", "NE", "SW", "SE", ] # directions considered "ahead" for planning filters. Other values "behind"

# Collision Avoidance Configuration
collision_avoidance:
  direct_collision_avoidance: True # Enable or disable direct collision avoidance
  collision_prediction: True       # Enable or disable collision prediction

use_cool4_speed_profile:
  enable: True
