# Logger module configuration

logger_module:
  state: ON # ON/OFF
  intersection: '2' # Kakaiken: 2 - Ganken: 1
  scenario: '2' # scenario number
  log_time_interval: 0.1
  # log_speed: None
  # log_traffic_signal_state: None
  # log_position: None
  # log_other_vehicles: None

  # TF frames to publish and log each timestamp.
  # If "tree" is omitted, logger loads transforms from source_config.
  tf_logging:
    enabled: true
    publish_tf: true
    source_config: sensors_calibration.yaml
    root_frame: base_link
    tree:
      base_link:
        bus_front:
          x: 7.25
          y: 0.0
          z: 0.0
          roll: 0.0
          pitch: 0.0
          yaw: 0.0
        bus_tail:
          x: -3.15     # forward (meters)
          y: 0.0      # lateral offset if any
          z: 0.0     # height above vehicle ref point
          roll: 0.0   # orientation if sensor is tilted
          pitch: 0.0
          yaw: 0.0
        isuzu_bus_front:
          x: 6.165    # forward (meters)
          y: 0.0      # lateral offset if any
          z: 0.0     # height above vehicle ref point
          roll: 0.0   # orientation if sensor is tilted
          pitch: 0.0
          yaw: 0.0
        isuzu_bus_tail:
          x: -2.69     # forward (meters)
          y: 0.0      # lateral offset if any
          z: 0.0     # height above vehicle ref point
          roll: 0.0   # orientation if sensor is tilted
          pitch: 0.0
          yaw: 0.0

  # Points to log when the vehicle approaches them.
  # Distance threshold is in meters.
  logging_points:
    default_threshold: 1.0
    points:
      - name: "I2_ZE_E_BusHead"
        x: 4525.74
        y: 72947.64
        z: 18.63
        threshold: 1.0
      - name: "I2_ZE_E_BusRearWheel"
        x: 4519.52
        y: 72943.90
        z: 18.63
        threshold: 1.0
      - name: "I2_ZN_S_BusRearWheel"
        x: 4496.31
        y: 72947.96
        z: 18.76
        threshold: 1.0
      - name: "I2_ZN_N_BusTail"
        x: 4493.42
        y: 72954.55
        z: 18.76
        threshold: 1.0
      - name: "after_30km"
        x: 4440.0
        y: 73090.0
        z: 18.62
        threshold: 1.0
