vehicles:
  lexus:
    model: "RX450H"
    dimensions:
      length: 4.8895  # Vehicle length (meters)
      width: 1.895    # Vehicle width (meters)
      height: 1.6     # Vehicle height (meters)
      wheel_base: 2.75 # Distance between front and rear axles (meters)
      front_overhang: 1.0 # Distance from front axle to vehicle front (meters)
      rear_overhang: 1.0  # Distance from rear axle to vehicle back (meters)
    weight: 3000  # Vehicle weight (kg)
    performance:
      max_speed: 20.0         # Maximum speed (m/s)
      min_speed: 0.83          # Minimum speed (m/s)
      middle_speed: 3.33          # Middle speed (m/s)
      acceleration_rate: 3.8     # acceleration rate (m/s²)
      normal_deceleration_rate: -1.0 # Normal deceleration (m/s²)
      max_braking_deceleration_rate: -3.0 # Maximum braking acceleration (m/s²)
      emergency_braking_deceleration_rate: -5.0 # Maximum braking acceleration (m/s²)

  bus:
    model: "TierIV"
    dimensions:
      length: 10.3   # Vehicle length (meters)
      width: 2.9     # Vehicle width (meters)
      height: 3.2    # Vehicle height (meters)
      wheel_base: 4.8 # Distance between front and rear axles (meters)
      front_overhang: 2.3 # Distance from front axle to vehicle front (meters)
      rear_overhang: 3.2  # Distance from rear axle to vehicle back (meters)
    weight: 10000  # Vehicle weight (kg)
    performance:
      max_speed: 8.33         # Maximum speed (m/s)
      min_speed: 0.83          # Minimum speed (m/s)
      middle_speed: 3.33          # Middle speed (m/s)
      acceleration_rate: 0.5     # Acceleration rate (m/s²)
      normal_deceleration_rate: -0.15 # Normal deceleration (m/s²)
      max_braking_deceleration_rate: -0.25 # Maximum braking deceleration (m/s²)
      emergency_braking_deceleration_rate: -1.0 # Maximum braking deceleration (m/s²)
