# フリースペース ID
dm_object_info_msgs/ObjectId id
# 情報取得時刻
dm_object_info_msgs/TimestampIts time
# リビジョン番号
dm_object_info_msgs/Revision revision
# 検知方法
DetectionMethod detection_method
# 検知可能物標種別
DetectableClasses detectable_classes
# ポリゴン
Vertices vertices
# 始点位置
dm_object_info_msgs/Location position_begin
# 終点位置
dm_object_info_msgs/Location position_end
# 長さ
dm_object_info_msgs/ObjectDimension length
# 始点物標 ID
dm_object_info_msgs/ObjectId id_begin
# 終点物標 ID
dm_object_info_msgs/ObjectId id_end
# 存在信頼度
dm_object_info_msgs/ExistenceConfidence existency
# 検知漏れ物標サイズ
dm_object_info_msgs/ObjectDimensionValue minimal_detectable_size
# 情報源のリス
dm_object_info_msgs/ObjectId[] information_source_list
