motion:
  max_turning_angle: 35.0  # degrees, maximum turning angle allowed
  speed_limits:
    urban: 15.0  # m/s
    highway: 30.0  # m/s
  
behaviour:
  saftey_distance: 8.0  # meters, minimum distance to stop behind an object
  reaction_time_threshold: 5  # seconds, time delay before reacting to an event