vehicles:
  lexus:
    model: "RX450H"
    dimensions:
      length: 4.8895  # Vehicle length (meters)
      width: 1.895    # Vehicle width (meters)
      height: 1.6     # Vehicle height (meters)
      wheel_base: 2.75 # Distance between front and rear axles (meters)
    weight: 3000  # Vehicle weight (kg)
    performance:
      max_speed: 30.0          # Maximum speed (m/s)
      max_acceleration: 3.8     # Maximum acceleration (m/s²)
      max_braking_acceleration: -6.0 # Maximum braking acceleration (m/s²)

  bus:
    model: "TierIV"
    dimensions:
      length: 10.3   # Vehicle length (meters)
      width: 2.9     # Vehicle width (meters)
      height: 3.2    # Vehicle height (meters)
      wheel_base: 4.8 # Distance between front and rear axles (meters)
      front_overhang: 2.3 # Distance from front axle to vehicle front (meters)
      rear_overhang: 3.2  # Distance from rear axle to vehicle back (meters)
    weight: 10000  # Vehicle weight (kg)
    performance:
      max_speed: 20.0          # Maximum speed (m/s)
      max_acceleration: 1.6     # Maximum acceleration (m/s²)
      max_braking_acceleration: -3.2 # Maximum braking acceleration (m/s²)
